const mongoose = require('mongoose');

const refundSchema = new mongoose.Schema({
    order: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Order',
        required: true
    },
    user: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true
    },
    product: {
        // If null, it refers to the whole order
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Product'
    },
    transaction: { // Link to original transaction if available
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Transaction'
    },

    // Financials
    amount: {
        type: Number,
        required: true
    },
    refundPercentage: {
        type: Number
    },

    // Details
    reason: {
        type: String,
        required: true
    },
    description: {
        type: String // User provided detailed description
    },
    images: [{ type: String }], // Evidence images

    // Logistics
    gateway: {
        type: String,
        enum: ['Razorpay', 'Stripe', 'PayPal', 'COD', 'Bank Transfer', 'Wallet'],
        required: true
    },
    bankAccountDetails: {
        type: String // Encrypted or JSON string if needed for manual transfer
    },

    // Admin Process
    status: {
        type: String,
        enum: ['Pending', 'Approved', 'Processed', 'Rejected'],
        default: 'Pending'
    },
    adminNote: {
        type: String
    },
    processedBy: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User'
    },
    refundTransactionId: {
        type: String // The ID generated by the gateway upon refund success
    }

}, { timestamps: true });

module.exports = mongoose.model('Refund', refundSchema);
